Starting job 1480400 on gpu-11 on fox at Sun Mar 30 20:04:13 CEST 2025

Number of available GPUs: 4
GPU 0: NVIDIA GeForce RTX 3090
GPU 1: NVIDIA GeForce RTX 3090
GPU 2: NVIDIA GeForce RTX 3090
GPU 3: NVIDIA GeForce RTX 3090
[W socket.cpp:426] [c10d] The server socket has failed to bind to [::]:12355 (errno: 98 - Address already in use).
[W socket.cpp:426] [c10d] The server socket has failed to bind to 0.0.0.0:12355 (errno: 98 - Address already in use).
[E socket.cpp:462] [c10d] The server socket has failed to listen on any local network address.
Traceback (most recent call last):
  File "/cluster/software/EL9/easybuild/software/Python/3.10.8-GCCcore-12.2.0/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/cluster/software/EL9/easybuild/software/Python/3.10.8-GCCcore-12.2.0/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/fp/projects01/ec232/torfor/learnableTokenizer/src/differentiableTokenizer/train.py", line 62, in <module>
    mp.spawn(main, args=(world_size, sys.argv[1:]), nprocs=world_size)
  File "/fp/projects01/ec232/venvs/g01env/lib/python3.10/site-packages/torch/multiprocessing/spawn.py", line 239, in spawn
    return start_processes(fn, args, nprocs, join, daemon, start_method='spawn')
  File "/fp/projects01/ec232/venvs/g01env/lib/python3.10/site-packages/torch/multiprocessing/spawn.py", line 197, in start_processes
    while not context.join():
  File "/fp/projects01/ec232/venvs/g01env/lib/python3.10/site-packages/torch/multiprocessing/spawn.py", line 160, in join
    raise ProcessRaisedException(msg, error_index, failed_process.pid)
torch.multiprocessing.spawn.ProcessRaisedException: 

-- Process 2 terminated with the following error:
Traceback (most recent call last):
  File "/fp/projects01/ec232/venvs/g01env/lib/python3.10/site-packages/torch/multiprocessing/spawn.py", line 69, in _wrap
    fn(i, *args)
  File "/fp/projects01/ec232/torfor/learnableTokenizer/src/differentiableTokenizer/train.py", line 17, in main
    ddp_setup(rank, world_size)
  File "/fp/projects01/ec232/torfor/learnableTokenizer/src/train_utils.py", line 30, in ddp_setup
    init_process_group(backend="gloo", rank=rank, world_size=world_size)
  File "/fp/projects01/ec232/venvs/g01env/lib/python3.10/site-packages/torch/distributed/distributed_c10d.py", line 907, in init_process_group
    default_pg = _new_process_group_helper(
  File "/fp/projects01/ec232/venvs/g01env/lib/python3.10/site-packages/torch/distributed/distributed_c10d.py", line 1009, in _new_process_group_helper
    backend_class = ProcessGroupGloo(backend_prefix_store, group_rank, group_size, timeout=timeout)
RuntimeError: [../third_party/gloo/gloo/transport/tcp/pair.cc:799] connect [10.110.0.81]:44464: Connection refused


Job 1480400 consumed 0.2 billing hours from project ec232.

Submitted 2025-03-30T20:04:10; waited 3.0 seconds in the queue after becoming eligible to run.

Requested wallclock time: 2.0 days
Elapsed wallclock time:   14.0 seconds

Job failed.

Task and CPU statistics:
ID             CPUs  Tasks  CPU util                Start  Elapsed  Exit status
1480400           4            0.0 %  2025-03-30T20:04:13   14.0 s  1
1480400.batch     4      1    53.0 %  2025-03-30T20:04:13   14.0 s  1

Used CPU time:   29.7 CPU seconds
Unused CPU time: 26.3 CPU seconds

Memory statistics, in GiB:
ID              Alloc   Usage
1480400         100.0        
1480400.batch   100.0     0.0

Job 1480400 completed at Sun Mar 30 20:04:27 CEST 2025
